JEOLLOGA/JEOLLOGA-CLIENT

- package.json
- tsconfig.app.json
- vite.config.ts
- yarn.lock
close #13 
- import 절대경로 설정
- `vite-tsconfig-paths` 플러그인 사용해서 절대경로 지정해주었습니다 ~ 스크린샷 첨부합니다 ! 
> 기록하며 개발하기!
- 
-
> [INIT] import 절대경로 설정

- src/components/detailTitle/DetailTitle.tsx
- src/components/detailTitle/detailTitle.css.ts
- src/stories/DetailTitle.stories.ts
close #60 
- 상세 페이지의 제목 공통 컴포넌트 구현했습니다.
- title이 리뷰이고, 리뷰 개수가 1개 이상일때 전체보기 버튼이 나타나야 해서 어떻게 로직을 짤까 고민했는데 리드님이 말해주신 것처럼 isTotal이라는 boolean값을 true로 받아올 때만 전체보기 버튼이 나타나도록 구현했습니다.
> 기록하며 개발하기!
- 
- 
하얀색 배경이라 잘 안보여서 border를 잠깐 추가했습니다
> [FEAT] 상세 페이지 제목 공통 컴포넌트 구현

- src/components/common/button/infoBtn/InfoBtn.tsx
- src/components/common/button/infoBtn/infoBtn.css.ts
- src/stories/InfoBtn.stories.ts
close #74 
- 마이페이지 InfoBtn 컴포넌트 구현
- 해당 컴포넌트는 마이페이지 > 도움말에서 사용되는 컴포넌트입니다 ! 공지사항, 문의하기 두 개가 있어서 구분선이 필요한데, 이는 hasDivider라는 boolean 값을 이용해 제어하도록 구현했습니다. (hasDivider가 true일 경우 버튼 아래에 구분선을 표시, default는 false) 피그마에서는 구분선이 포함된 형태로 컴포넌트가 정의되어 있지만, 구분선이 없는 경우도 고려해야 했기에 위와 같은 방식으로 작업했습니다 ~~ 더 나은 방법이 있다면 피드백 부탁드림니다 🥸
> 기록하며 개발하기!
- 
-
> [FEAT] InfoBtn 컴포넌트 구현

- package.json
- src/App.tsx
- src/main.tsx
- src/pages/ErrorPage.tsx
- src/pages/HomePage.tsx
- src/pages/SearchPage.tsx
- src/router/Router.tsx
- src/styles/global.css.ts
- yarn.lock
close #81
- router 세팅을 진행하였습니다.
- lazy를 통해 페이지 컴포넌트를 동적으로 로드하여 초기 번들 크기를 줄이고 필요할 때만 해당 모듈을 가져오도록 하였습니다.
- lazy로 로드된 컴포넌트를 suspense로 감싸서 컴포넌트가 로드될 때까지 사용자에게 로딩 화면을 보여주도록 하였습니다.
- outlet에 margin: 0 auto를 주어서 해당 컴포넌트가 화면의 가운데에 위치할 수 있도록 하였습니다.
- 디자인 선생님들께 말씀 드려서 페이지의 margin-top은 12px로 고정해놔서 해당 값도 함께 추가하였습니다.
- 유효하지 않은 url주소로 갈시 main으로 리다이렉트되도록 설정하였습니다.
- header와 footer가 반복적으로 사용되었다면 app에 header와 footer를 지정해 놓거나, header와 footer를 따로 받아서 children으로 넣을지에 대해서 고민해보았는데 화면마다 헤더의 값에 서버 데이터가 들어가기도 하고, header는 화면중에 1번, footer은 2개의 화면에만 존재해서 각 화면에서 정의하는 것이 나을것이라 생각하여 header와 footer를 공통적으로 app에 정의하지 않았습니다.
> 기록하며 개발하기!
https://codeparrot.ai/blogs/createbrowserrouter-a-step-up-from-switch …
> [FEAT] router 세팅

- src/assets/svgs/icn_reset.svg
- src/components/common/button/buttonBar/ButtonBar.tsx
- src/components/common/button/buttonBar/buttonBar.css.ts
- src/components/common/button/flowerBtn/FlowerBtn.tsx
- src/components/common/button/flowerBtn/flowerBtn.css.ts
- src/components/common/button/pageBottomBtn/PageBottomBtn.tsx
- src/components/common/button/textBtn/TextBtn.tsx
- src/components/common/button/textBtn/textBtn.css.ts
- src/components/common/icon/FlowerIcon.tsx
- src/stories/ButtonBar.stories.ts
- src/stories/FlowerBtn.stories.ts
close #77
- ButtonBar 컴포넌트 퍼블리싱을 하였습니다.
- flowerBtn 컴포넌트를 구현하였습니다. 
- 기존의 TextBtn이 size에 따라서 색상이 다르게 설정되어서 해당 컴포넌트 스타일을 수정하였습니다.
- BottomBar 버튼이 reset인 경우와 wish인 경우 2가지로 나누었는데 확장성이 떨어진다고 생각이 들긴하지만 일단 이렇게 만들었습니다. 더 좋은 방식이 있다고 생각하시면 말씀해주세요!
> 기록하며 개발하기!
- 
- 
- bottomBtn
- flowerBtn
> [FEAT] ButtonBar 컴포넌트 퍼블리싱

- src/components/carousel/curationCarousel/CurationCarousel.tsx
- src/components/carousel/curationCarousel/curationCarousel.css.ts
- src/components/curation/curationCard/curationCard.css.ts
- src/components/search/recentBtn/recentBtnBox.css.ts
- src/constants/curationInfo.ts
- src/stories/CurationCarousel.stories.ts
- src/styles/global.css.ts
- src/utils/registDragEvent.ts
close #82 
- 홈페이지 > 큐레이션 캐러셀 퍼블리싱 완료했습니다
- 일정 거리 이상 드래그 되면 다음 큐레이션 카드로 넘어가도록 구현했습니다
- 큐레이션 관련 데이터는 서버에서 받아오는 것이 아니기 때문에 , constant 폴더에 따로 빼두었습니다.
- 해당 섹션의 타이틀(절로가 큐레이션)을 캐러셀 컴포넌트 안에 포함시킬지 말지 고민중입니닷
- 아래 첨부한 아티클을 많이 참고했는데, 드래그 이벤트 관리하는 함수를 빼두는 게 다른 캐러셀에서도 사용할 수 있을 것 같아 유틸로 만들어두었습니다 , ,
- 해당 캐러셀의 경우 `드래그 -> 캐러셀 이동`, `클릭 -> 큐레이션 페이지로 이동` 의 두 가지 조건을 모두 만족해야 했기 때문에, 100을 기준으로 드래그 / 클릭을 구분하였습니다 ! 여러 값으로 테스트 해본 결과 가장 적당하다고 판단해서 100을 기준으로 하였는데 너무 낮거나 높다고 생각되면 피드백 부탁드립니다. 
> 기록하며 개발하기!
- 
- [Drag Carousel 뽀개기](https://velog.io/@bepyan/Drag-Carousel-%EB%BD%80%EA%B0%9C%EA%B8%B0)
- [[JS] 클릭과 드래그 이벤트 구분하기(React)](https://velog.io/@postlist/JS-%ED%81%B4%EB%A6%AD%EA%B3%BC-%EB%93%9C%EB%9E%98%EA%B7%B8-%EC%9D%B4%EB% …
> [FEAT] 큐레이션 캐러셀 퍼블리싱

- src/components/carousel/curationCarousel/CurationCarousel.tsx
- src/components/carousel/popularCarousel/CarouselIndex.tsx
- src/components/carousel/popularCarousel/PopularCarousel.tsx
- src/components/carousel/popularCarousel/carouselIndex.css.ts
- src/components/carousel/popularCarousel/popularCarousel.css.ts
- src/hooks/useCarousel.ts
- src/stories/CarouselIndex.stories.ts
- src/stories/PopularCarousel.stories.ts
- src/styles/global.css.ts
- src/utils/registDragEvent.ts
close #100 
- 인기스테이 캐러셀 퍼블리싱 완료했습니다.
- 해당 캐러셀 컴포넌트 아래에 위치한 캐러셀 인덱스 퍼블리싱 완료했습니다 (합치는 건 페이지 퍼블리싱에서 할 예정)
- 캐러셀 컴포넌트를 구현할 때 사용할 수 있는 useCarousel 커스텀 훅을 작성하였습니다 ! 전체적으로 상태를 관리하고, 드래그 동작을 처리하며, 스타일과 동작을 제어하는 로직들을 분리해두었습니당 ~
- registDragEvent 함수에 touch 이벤트(onTouchStart, onTouchMove, onTouchEnd) 처리 로직 추가 -> 데스크톱과 모바일 모두에서 캐러셀 동작 가능하도록 수정하였습니다
> 기록하며 개발하기!
- Mouse Evenㅅ와 Touch Event의 차이점에 대해 알게되었습니다.
- 모바일 웹에서는 Touch Event까지 함께 관리해주어야 한다는 점을 알게 되었습니다 , , ,
- [[Web] Mouse Event, Touch Event, Pointer Event, Drag Event 비교](https://velog.io/@jsi06138/Web-Mouse-Drag-Pointer)
> [FEAT] 인기스테이 캐러셀 구현

- src/components/card/lookCard/lookCard.css.ts
- src/components/card/mapCard/map.css.ts
- src/components/card/mapCard/mapCard.css.ts
- src/components/carousel/curationCarousel/curationCarousel.css.ts
- src/components/carousel/popularCarousel/carouselIndex.css.ts
- src/components/footer/footer.css.ts
- src/pages/HomePage.tsx
- src/pages/homePage/HomePage.tsx
- src/pages/homePage/homePage.css.ts
- src/router/Router.tsx
- src/stories/HomePage.stories.ts
close #114 
- 메인페이지 퍼블리싱 완료했습니다
- 각 컴포넌트 사이의 간격이 일정하지 않아서, 일일히 gap을 주려면 div가 너무 많아질 것 같아, 재사용되지 않고 메인페이지 내에서만 사용되는 컴포넌트 (템플스테이 보러가기 버튼, 지도 등) 자체에 margin을 설정해준 부분이 있습니다. 괜찮을까용 ?
> 기록하며 개발하기!
- 
https://github.com/user-attachments/assets/78ba2196-7139-406d-9cd5-d3b95890121a
> [FEAT] 메인페이지 퍼블리싱

- src/apis/ranking/axios.ts
- src/apis/ranking/index.ts
- src/apis/ranking/type.ts
- src/components/carousel/popularCarousel/PopularCarousel.tsx
close #129 
- 이번주 인기 스테이 불러오기 api 연결했습니다
- 필드값에 오류가 있어서 스크린샷 상에서 사진이 안 보이는게 맞습니다. imgUrl 필드에서 템플스테이 이미지의 url이 아닌 템플스테이의 url이 반환되고 있기 때문인데, 해당 부분은 서버측에 수정 요청 드린 상태라 반영 되면 정상적으로 사진이 보일 것 같습니다 (네트워크 탭에서 데이터 제대로 오는 것 확인했습니당 ~)
- 캐러셀 위치가 요상한건 아직 메인페이지 디벨롭에 머지되기 전에 브랜치 파서 작업한거라 컴포넌트를 빈 페이지에 불러와서 테스트하느라 그래요 호호호
> 기록하며 개발하기!
- 매개변수 타입 지정을 정확히 해주자 . !!!!!!!!!!
-
> [FEAT] 이번주 인기 스테이 불러오기 api 연결

- src/apis/user/axios.ts
- src/apis/user/index.ts
- src/apis/user/type.ts
- src/pages/homePage/HomePage.tsx
- src/pages/onboardingPage/OnboardingPage.tsx
- src/pages/welcomePage/WelcomePage.tsx
close #136 
- 사용자 닉네임을 받아서 띄우는 api 연결
- 홈페이지 LookCard에 닉네임 적용
- 온보딩 페이지에 닉네임 적용
- 온보딩 마지막 단계 후 로컬스토리지에 저장되어있던 사용자 정보 정송 api 연결
- 간단한 api들이라 React Query 장점이 없는 것 같아 axios로만 할지 고민했지만, 우선은 React Query로 구현하였습니다.
- 수정사항 있으면 말씀해주세요
> 기록하며 개발하기!
- 
- 
https://github.com/user-attachments/assets/f428dd77-6219-4bcd-8329-c53a47654a1a
> [FEAT] 사용자 닉네임 반환, 온보딩 정보 전송 api 연결

- src/components/card/lookCard/LookCard.tsx
- src/components/common/empty/filterEmpty/FilterEmpty.tsx
- src/components/common/empty/searchEmpty/SearchEmpty.tsx
- src/components/except/exceptLayout/ExceptLayout.tsx
- src/components/header/Header.tsx
- src/components/header/header.css.ts
- src/pages/loginPage/LoginPage.tsx
- src/pages/welcomePage/WelcomePage.tsx
close #166 
- 로티가 상황에 맞게 변경되지 않고 하나만 뜨는 문제를 해결하기 위해 key값 추가했습니다.
- 홈페이지 헤더 검색 아이콘 하나 삭제
- 헤더 로고 클릭 시 홈페이지 이동 추가
- 홈페이지 헤더 위시 아이콘 변경 및 위치 수정
- 
> 기록하며 개발하기!
- 
-
> [FIX] 로티 key 추가 및 홈페이지 헤더 아이콘 수정

- src/apis/auth/index.ts
- src/apis/instance.ts
- src/apis/user/index.ts
- src/components/card/lookCard/LookCard.tsx
- src/main.tsx
- src/pages/HomePage.tsx
- src/pages/homePage/HomePage.tsx
- src/pages/onboardingPage/OnboardingPage.tsx
close #172
- 처음 로그인 하는 유저 온보딩 페이지로 이동
- 닉네임 가져오는 api useQuery로 로딩 붙여서 데이터 받아와야 이름 보이도록 설정
- 
> 기록하며 개발하기!
- 
-
> [FEAT] 첫 로그인한 유저인 경우 온보딩 페이지로 이동 로직 구현

- src/apis/templeDetail/axios.ts
- src/apis/templeDetail/index.ts
- src/components/common/pageName/PageName.tsx
- src/pages/templeDetailPage/TempleDetailPage.tsx
- getAxiosInstance 필요한 부분 적용햇슴다
- 
> 기록하며 개발하기!
- 
-
> [FEAT] getAxiosInstance 필요한 부분 적용

- src/components/card/popularCard/PopularCard.tsx
- src/components/card/templeStayCard/TempleStayCard.tsx
- src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
- src/components/carousel/popularCarousel/PopularCarousel.tsx
- src/components/common/button/buttonBar/buttonBar.css.ts
- src/components/common/modal/modal.css.ts
- src/components/common/pageName/PageName.tsx
- src/components/templeDetail/templeTopbar/TempleTopbar.tsx
- src/pages/homePage/HomePage.tsx
- src/pages/homePage/homePage.css.ts
- src/pages/loginPage/LoginPage.tsx
- src/pages/searchResultPage/SearchResultPage.tsx
- src/pages/searchResultPage/searchResultPage.css.ts
- src/pages/templeDetailPage/TempleDetailPage.tsx
- src/stories/PopularCarousel.stories.ts
close #194 
- 로그인하지 않은 사용자가 찜하기 버튼을 누르면 모달창이 뜨도록 모든 곳을 연결했습니다.
- 모달의 백드롭이 웹 전체화면에 떠서 화면에 맞게 조정하였습니다.
- 모달창에서 로그인하기 버튼을 누르면 현재는 위시리스트를 누를때와 동일한 로그인 연결 페이지가 뜹니다.
- 상세페이지에서 상단 헤더의 위시 아이콘은 찜하기 기능이 아니라 위시리스트로 연결되도록 수정하였습니다.
- 수정사항 있으면 말씀해주세요.
> 기록하며 개발하기!
- 
-
> [FEAT] 비로그인 위시 클릭 시 로그인 연결

- src/hooks/useCarousel.ts
- src/pages/CurationPage/CurationPage.tsx
- src/pages/CurationPage/curationPage.css.ts
- src/router/Router.tsx
close #196 
- 캐러셀 감도 50으로 줄였습니다.
- 큐레이션 탑바 상단 고정시켰습니다.
- 
> 기록하며 개발하기!
- 
-
> [FIX] 큐레이션 탑바 상단 고정, 캐러셀 감도 조절

- src/components/carousel/curationCarousel/CurationCarousel.tsx
- src/components/carousel/detailCarousel/DetailCarousel.tsx
- src/components/carousel/detailCarousel/DetailImage.tsx
- src/components/common/detailInfo/detailInfo.css.ts
- src/components/common/tapBar/TapBar.tsx
- src/components/filter/filterTypeBox/filterTypeBox.css.ts
- src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
- src/components/templeDetail/stickyTapBar/StickyTapBar.tsx
- src/components/templeDetail/templeInfo/templeInfo.tsx
- src/components/templeDetail/templePrice/TemplePrice.tsx
- src/components/templeDetail/templeReview/TempleReview.tsx
- src/components/templeDetail/templeSchedule/TempleSchedule.tsx
- src/components/templeDetail/templeTitle/TempleTitle.tsx
- src/components/templeDetail/templeTitle/templeTitle.css.ts
- src/components/templeDetail/templeTopbar/templeTopbar.css.ts
- src/hooks/useMoveScroll.ts
- src/pages/searchResultPage/searchResultPage.css.ts
- src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
- src/pages/templeDetailPage/blogReview/blogReviewPage.css.ts
- src/pages/templeDetailPage/templeDetailPage.css.ts
- src/pages/templeDetailPage/templePhoto/TemplePhotoPage.tsx
- src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts
close #208 
- 상세페이지 사찰 이미지 null일시 대체 이미지 처리했습니다.
- 상세페이지 전화번호 줄 넘어갈시 ... 대체했습니다.
- 큐레이션 클릭시 페이지 상단으로 스크롤하도록 했습니다.
- 탭바 스크롤을 type에 따라 
`.getBoundingClientRect().bottom` `.getBoundingClientRect().top`로 각각 다르게 적용되도록 하여 상세페이지에서 보다 알맞게 움직이도록 적용했습니다.
- 블로그, 사진, 큐레이션, 사찰 검색 뷰 탑바 상단 고정했습니다.
- 상단 탑바가 공통 컴포넌트이긴 한데 이미 상단 고정을 적용한 것도 있고 각각 다르게 페이지에서 적용되어 있어서 공통으로 못빼고 각자 적용시켰는데 추후에 리팩토링하겠습니다 죄송합니다🥹🥹🥹🥹🥹🥹🥹
> 기록하며 개발하기!
- 
-
> [FIX] 상세페이지 2차 

- src/components/card/templeStayCard/TempleStayCard.tsx
- src/components/card/templeStayCard/wishCardList/WishCardList.tsx
- src/components/schedule/scheduleCard.css.ts
- src/pages/wishList/WishListPage.tsx
close #228 
- 위시리스트에서 상세 페이지로 라우팅 안되는 이슈 해결
- 
> 기록하며 개발하기!
- 
-
> [FIX] QA 4차반영

- src/components/common/tapBar/TapBar.tsx
- src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
- src/components/templeDetail/templeInfo/templeInfo.tsx
- src/components/templeDetail/templePrice/TemplePrice.tsx
- src/components/templeDetail/templeReview/TempleReview.tsx
- src/components/templeDetail/templeSchedule/TempleSchedule.tsx
- src/hooks/useMoveScroll.ts
close #236 
- 탭바 스크롤바 이동 문제 수정했습니다
- 
> 기록하며 개발하기!
- 
-
> [FIX] QA 5차 대응 

- .github/workflows/auto-sync.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/vercel-deploy.yml
close #250
- 현재 develop브랜치에 push할시 fork된 브랜치로 동기화는 잘 일어나지만 vercel 배포는 일어나지 않아서 이를 해결하고자 vercel preview 배포 전용 workflow 추가하였습니다.
- 해당 workflow의 내용은 fork된 레파지토리에서 develop브랜치의 push가 일어날 시 Vercel Preview 배포가 자동 실행되게 하는 workflow입니다.
```
Auto-assign Custom Production Domains
Automatically assign custom domains after each deployment triggered by a merge to the production branch or a Vercel CLI deploy with the --prod flag.
```
해당 내용은 production 브랜치에 머지되거나 vercel --prod명령어를 통해 배포될때는 vercel이 설정된 커스텀 도메인을 자동으로 적용한다는 의미 입니다. 이를 통해서 preview 배포의 경우 직접 배포를 트리거해주면 자동 배포가 일어나지 않을까 생각하여 해당 workflow를 추가하게 되었습니다.
- 
> 기록하며 개발하기!
- 
-
> [CI/CD] vercel preview 배포 전용 workflow 추가

- .github/workflows/deploy-preview.yml
close #256
- develop브랜치로 push한 경우 preview 배포가 이루어진다고 생각했지만 sorce는 develop가 맞아도 계속해서 develop으로부터 production환경으로 배포가 진행되는 문제가 있었습니다.
- Preview 환경으로 배포하기 위해 기존에 사용한 코드는 다음과 같습니다.
```
run: vercel --token=${{ secrets.VERCEL_TOKEN }} --prod=false --yes
```
- `--prod=false`를 사용하면 Preview 배포가 이루어진다고 생각했으나 실제로는 계속 Production 환경으로 배포되었어요.(지피티가 이렇게 하면 된다고 해서 이렇게 넣었던 저를 반성합니다.)
- 문제를 해결하기 위해 Vercel CLI 공식 문서를 확인한 결과,  아래와 같이 `--target` 옵션을 사용하면 배포할 환경을 지정할 수 있다는 설명이 있었습니다. 
```
Use the --target option to define the environment you want to deploy to. This could be production, preview, or a custom environment.
```
- `--prod=false `대신 `--target=preview`를 사용하여 Preview 환경으로 명확하게 배포하도록 수정했어요!
-  다음과 같이 수정
```
run: vercel --token=${{ secrets.VERCEL_TOKEN }} …
```
> [CI/CD] preview가 아닌 production으로 배포되는 문제 해결하기

- src/apis/auth/axios.ts
- src/apis/auth/index.ts
- src/apis/instance.ts
- src/pages/RedirectionPage/RedirectionPage.tsx
close #244 
- 로그인 API 수정사항에 맞춰 코드 리팩토링을 진행하였습니다. 
🛠️ 작업 목록
- 로그인 get -> post 수정 및 redirectUri 필드 추가
- accessToken 재발급 엔드포인트 수정
- 서버 측 요청에 따라 로그인 요청을 보낼 때 redirectUri도 함께 보내도록 수정했습니다. 해당 부분에서 고정된 값(redirectUri)을 클라 측에서 로그인 할 때마다 보내주어야 할 필요가 있는가 ? 에 대해 의문이 들어 서버 측에 여쭤봤는데, 로컬, 배포환경일 때마다 yml 파일을 변경해야 하는 번거로움이 있어 클라에서 redirectUri를 직접 전달하는 방식으로 수정하였다고 합니다 ~! 참고하세염
- 로그인 잘 되는지 테스트 한 번씩만 해주세요 !!!!!! (_ _)
> 기록하며 개발하기!
- 
- 
https://github.com/user-attachments/assets/f668420f-d0d9-4f1b-b0af-9e72df455efe
> [REFACTOR] 로그인 리팩토링

- index.html
- robots.txt
- sitemap.xml
- src/components/card/lookCard/LookCard.tsx
- src/components/card/lookCard/lookCard.css.ts
- src/components/card/mapCard/MapCard.tsx
- src/components/card/popularCard/PopularCard.tsx
- src/components/card/templeStayCard/TempleStayCard.tsx
- src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
- src/components/card/templeStayCard/wishCardList/WishCardList.tsx
- src/components/carousel/curationCarousel/CurationCarousel.tsx
- src/components/carousel/popularCarousel/PopularCarousel.tsx
- src/components/curation/curationCard/CurationCard.tsx
- src/components/detailTitle/DetailTitle.tsx
- src/pages/wishList/WishListPage.tsx
- src/stories/CurationCard.stories.ts
- src/stories/PopularCard.stories.ts
- src/stories/TempleStayCard.stories.ts
close #245
- robots.txt 파일을 추가하였습니다.
- 모든 검색엔진봇을 허용 (`User-agent: *`) 
- 검색 엔진 색인 제외 페이지 (login, loginStart 등등)
- sitemap 추가
- sitemap.xml 파일을 추가하였습니다. 
- 해당 파일은 www.xml-sitemaps.com를 통해 만들었고 현재는 메인페이지에 대한 sitemap만을 추가해두었습니다. 추후에 다른 페이지에 대한 추가도 필요할 것으로 보입니다.
- header 시맨틱 태그가 기존에(main페이지에 한해서) 사진과 같이 h1없이 h2로 원하는 지역을 골라보세요가 헤더로 되어 있어서 해당 부분을 
아래와 같이 header 시맨틱 태그를 부여하였습니다.
- PopularCard와 CurationCard에에서 `<a>` 태그 적용하여 SEO 및 접근성 개선
- onClick 이벤트로 처리되던 네비게이션 로직을 href 속성으로 대체하여 SEO 친화적인 링크 구조 구현
- 이전의 코드는  div 및 button이 클릭 이벤트를 감지하는 방식이라 검색 엔진이 이 카드가 링크인지 인식하지 못한다는 점을 개선하고자 하였습니다.
- 
> 기록하며 개발하기!
- 기존에 저희 코드에서 링크의 이동인 경우에도 `button`또는 `div`태그에 `onClick` `naviagte`를 이용하여 `button`을 링크처럼 사용해왔었습니다. 하지만 이는 검색 엔진이 버튼이 링크 역할을 …
> [FEAT] robots.txt 및 메타태그 정보 추가

- src/components/card/popularCard/PopularCard.tsx
- src/components/card/templeStayCard/TempleStayCard.tsx
close #262 
- 템플스테이 카드 클릭 시 페이지 이동을 a태그로 바꾸면서, 위시리스트 담기 버튼을 클릭하는 경우 기존 e.stopPropagation();으로는 페이지 이동이 안 막아지던 문제를 e.preventDefault();를 추가하여 해결했습니다.
- 
> 기록하며 개발하기!
- preventDefault()를 사용하면 a태그의 기본 동작(페이지 이동)이 차단된다.
-
> [FIX] 템플스테이 카드 위시리스트 담기 클릭시 페이지 이동 막기 구현

- src/apis/auth/axios.ts
- src/apis/auth/index.ts
- src/apis/instance.ts
- src/pages/myPage/MyPage.tsx
close #264 
- 탈퇴 api를 구현했습니다.
- 탈퇴 후 홈페이지로 돌아올 때 401 Unauthorized 응답이 발생하여 alert가 떴지만, Authorization이 없는 경우에는 401을 감지해도 추가적인 처리를 하지 않도록 수정하여, alert가 뜨지 않도록 했습니다.
> 기록하며 개발하기!
- 
- 
https://github.com/user-attachments/assets/8bb87d1e-c95e-4f4b-b02d-f3c5305189d6
> [FEAT] 탈퇴하기 api 연결

- src/components/card/lookCard/LookCard.tsx
- src/components/card/mapCard/Map.tsx
- src/components/card/templeStayCard/TempleStayCard.tsx
- src/components/common/button/kakaoBtn/KakaoBtn.tsx
- src/components/common/empty/wishEmpty/WishEmpty.tsx
- src/components/common/tapBar/TapBar.tsx
- src/components/footer/Footer.tsx
- src/components/search/searchBar/SearchBar.tsx
- src/components/templeDetail/naverMap/smallMap/SmallMap.tsx
- src/components/templeDetail/templeReview/TempleReview.tsx
- src/components/userInfo/userInfo.tsx
- src/constants/regionInfos.ts
- src/gtm/GTMProvider.tsx
- src/gtm/hooks/useEventLogger.ts
- src/gtm/types.ts
- src/gtm/window.d.ts
- src/hooks/useExpandHook/useExpandHook.tsx
- src/main.tsx
- src/pages/filterPage/FilterPage.tsx
- src/pages/homePage/HomePage.tsx
- src/pages/myPage/MyPage.tsx
- src/pages/onboardingPage/OnboardingPage.tsx
- src/pages/searchResultPage/SearchResultPage.tsx
- src/pages/templeDetailPage/TempleDetailPage.tsx
- src/pages/welcomePage/WelcomePage.tsx
close #267
- GTM 스크립트를 삽입하는 GTMProvider 컴포넌트를 추가했어요.
- 클릭 이벤트를 dataLayer에 로깅하는 useEventLogger 커스텀 훅을 만들었어요.
- 기획에서 정의해준 이벤트 정의서를 기반으로 클릭 이벤트를 모두 심어두었어요! ga관련 자료는 [여기서](https://www.notion.so/GA-a3f4787f0e6d43cbab399ac47a69e9c7) 확인가능해요
- GTMProvider는 마운트 시점에 gtm.js 이벤트를 dataLayer에 푸시하고, <script> 태그를 생성해 GTM 스크립트를 동적으로 로드해요.
- useEventLogger는 현재 화면 이름(screen)과 window.location.pathname을 바탕으로 클릭 이벤트 정보를 생성하고, 이를 dataLayer에 푸시해요. 개발환경에선 콘솔에도 로깅되도록 했어요.
- 모든 클릭 이벤트에 대해서 로깅이 되는 것을 확인했어요.
> 기록하며 개발하기!
- 기획에서 정의해준 클릭 이벤트를 넣고 싶을때에는 
```
const { logClickEvent } = useEventLogger(기획이 작성해준 스크린명);
logClickEvent(이벤트 이름)
```
으로 사용하시면 됩니다! 
예시 코드를 보면 
위와 같은 이벤트를 추가하고자 할때는 
``` jsx
const { logClickEvent } = …
```
> [FEAT] GA 이벤트 태그 지정

- package.json
- src/app/searchResult/page.tsx
- src/components/common/bottmsheet/BottomSheet.tsx
- src/components/common/bottmsheet/bottomSheet.css
- src/components/common/button/basicBtn/basicBtn.css.ts
- src/components/common/button/textBtn/TextBtn.tsx
- src/components/common/button/underlinedBtn/underlinedBtn.css.ts
- src/components/common/pagination/Pagination.tsx
- src/components/common/tapBar/TapBar.tsx
- src/components/filter/filterBottomSheetModal/FilterBottomSheetModal.tsx
- src/components/filter/filterBottomSheetModal/FilterModalContent.tsx
- src/components/filter/filterBottomSheetModal/filterModal.css.ts
- src/components/filter/filterBottomSheetModal/filterModalContent.css.ts
- src/components/filter/filterTypeBox/FilterTypeBox.tsx
- src/components/templeDetail/templeInfo/contentCollapse/ContentCollapse.tsx
- src/constants/constants.ts
- src/hooks/useFilter.ts
- src/hooks/useMoveScroll.ts
- src/hooks/useScrollTrack.tsx
- src/styles/theme.css.ts
- yarn.lock
close #276
- react-modal-sheet을 사용해서 bottom sheet모달을 구현했어요.
- BottomSheet는 header와 children을 받아서 바텀 시트 모달이 구현 가능하도록 했어요.
- BottomSheet 컴포넌트를 사용해서 FilterBottomSheetModal을 구현했어요.
- 기존 tapbar의 경우에는 window를 기준으로 스크롤을 이동시켰는데 모달안에 필터들을 넣음으로서 window기준이 아니라 해당
모달을 기준삼아서 스크롤을 움직이기 위해서 scrollContainerRef를 옵셔널로 받아서 각 필터에 따라 모달내에서도 필터링이 움직일 수 있도록 구현했어요.
- react-modal-sheet의 스타일을 수정할때 !important를 사용하기 위해서 css로 스타일을 지정했어요. vallia-exract에서는 !important를 사용할 수 없는 것으로 알고 있는데 다른 방법 아신다면 말씀 부탁드립니다!
- 기본 BottomSheet 컴포넌트는 다음과 같은 형태이니 bottomSheet를 사용하실 때 아래와 같이 open관련 상태와 header, content만 넣어서 사용하시면 됩니다!
``` tsx
<BottomSheet
isOpen={isOpen}
onClose={handleCloseModal}
header={ // 바텀 시트에 header가 있는 경우는 header 넣기
<>
<h1 …
```
> [FEAT] 바텀시트 모달 UI 구현 및 필터 페이지를 필터 모달로 구현

- next.config.ts
- src/app/HomeClient.tsx
- src/app/homePage.css.ts
- src/app/page.tsx
- src/components/card/popularCard/PopularCard.tsx
- src/components/card/popularCard/popularCard.css.ts
- src/components/common/button/basicBtn/BasicBtn.tsx
- src/components/common/button/basicBtn/basicBtn.css.ts
- src/components/curation/curationCard/CurationCard.tsx
close #288 
- SSR 적용을 위한 홈페이지 클라이언트 컴포넌트 분리 (`HomeClient.tsx`)
- 홈페이지 캐러셀에서 사용되는 카드 컴포넌트의 이미지를 style backgroundImage -> `next/Image` 로 변경
- `BasicBtn` 아이콘 중앙 정렬 안되는 이슈 해결 (SSR 관련 태스크는 아닌데 거슬려서 같이함)
(정답이 없는 부분이라 제 생각과 고민 과정을 적어두었습니다)
홈페이지의 SSR 적용 및 성능 최적화를 위하여 기존 클라이언트 컴포넌트 중심 구조를 서버-클라이언트 분리 구조로 변경하였습니다. 
SSR 적용을 위해 해결이 필요했던 주요 항목들은 아래와 같았어요.
1. 유저 이름 받아오기
2. 인기 템플스테이 캐러셀
3. 모달 상태 관리
4. useEffect 내부의 초기화 코드들 (+ 로컬스토리지 prevPage 저장)
1,2번의 경우 현재는 로컬스토리지에서 토큰과 유저 아이디를 관리하고 있기 때문에 SSR 적용에 제약이 있어 todo로 남겨두었습니다.
(쿠키 기반 인증 방식 도입 이후 적용 예정 !)
3,4번을 두고 고민을 많이 했는데, 제가 생각한 해결책은 아래와 같았습니다.
- 모달 : Jotai를 사용해 전역 상태로 관리 / parallel routes / intercepting routes
- useEffect 내부의 초기화 코드들 : ?????
모달을 병렬 라우팅이나 인터셉트 라우팅으로 하기에는 이 모달을 위해 …
> [FEAT] 홈페이지 클라이언트 컴포넌트 분리 및 next/Image 적용
