JEOLLOGA/JEOLLOGA-CLIENT

.github/ISSUE_TEMPLATE/issue_template.yml

close #3
- 기능 설명, 작업 목록은 필수로 작성해야 하고 참고자료는 선택사항인 이슈 템플릿을 생성했습니다.
- 추가, 삭제, 수정하면 좋을 것 같은 부분 의견 주시면 반영하겠습니다!!
> 기록하며 개발하기!
- 
- 
- 이슈 작성 화면
- 이슈 생성 화면

[INIT] 이슈 템플릿 생성

---

.github/auto_assign.yml
.github/workflows/auto-sync.yml
eslint.config.js
src/stories/Button.tsx
src/stories/Header.tsx
src/stories/Page.stories.ts
src/stories/Page.tsx

close #22
- pr을 작성할 때 자동으로 reviewer를 등록하는 auto_assign.yml을 추가하였습니다.
- git action을 통해서 ci를 구현하고 vercel에서 제공하는 cd를 통해 배포도 자동화 하였습니다.
- **Auto Sync Workflow** : 
- main 브랜치의 변경 사항을 감지하여 포크된 저장소의 main 브랜치로 동기화.
- pull_request 이벤트에서 develop 브랜치로의 PR에 대한 lint 및 빌드 검증.
- 각 워크플로우에서 실행되는 작업
- **Cache Yarn Dependencies** : actions/cache를 사용하여 yarn 의존성 설치 속도를 최적화.
- **Build project** : 빌드 검증.
- **Lint Check** : lint 검증.
- build를 검증하는 작업은 Vercel에서 build가 성공하지 못하면 배포에 실패하기 때문에 꼭 필요한 작업니다!
- lint를 검증하는 작업은 저희 코드의 품질과 일관성을 높이고자 추가하였습니다.
> 기록하며 개발하기!
- CI/CD는 지속적 통합 (Continuous Integration)과 지속적 배포 (Continuous Deployment 또는 Continuous Delivery)의 약자입니다
- **CI** : 지속적 통합은 개발 팀이 코드를 지속적으로 통합하고, 이를 자동으로 테스트하여 통합 버그를 최소화하는 프로세스를 …

[CI/CD] github actions 워크플로우 추가

---

src/styles/fonts.css.ts
src/styles/theme.css.ts

close #28
- theme에 글꼴, 색상 추가했습니다
- 
> 기록하며 개발하기!
- 
-

[FEAT] theme 글꼴, 색상 추가

---

src/components/common/tag/Tag.tsx
src/components/common/tag/tag.css.ts
src/stories/Tag.stories.ts

close #53 
- 사라진 태그 컴포넌트 찾아왔습니다 
- 
> 기록하며 개발하기!
- 
-

[FIX] 태그 컴포넌트 부활시키기

---

src/components/common/detailInfo/DetailInfo.tsx
src/components/common/detailInfo/detailInfo.css.ts
src/stories/DetailInfo.stories.ts

close #52 
- 템스 상세 페이지에서 사용하는 info 컴포넌트 구현하였습니다 
- 
> 기록하며 개발하기!
- 
-

[FEAT] 상세 정보 컴포넌트 구현

---

src/constants/loginInfos.ts
src/pages/loginPage/loginPage.css.ts

close #125 
- 테스트용 dev to main 에서 발생한 이슈 두 가지 해결하였습니당
- 메인에서 로그인 창의 이미지 안 보이는 이슈 해결을 위해 img를 import해서 사용하는 방식으로 수정하였습니다.
- 로그인 페이지 레이아웃이 좌측으로 치우쳐져 보이는 것도 수정하였습니다 ! 
- 
> 기록하며 개발하기!
- 
-

[FIX] 메인에서 이미지 안 보이는 이슈 해결

---

src/components/curation/curationCard/curationCard.css.ts
src/components/footer/Footer.tsx

close #153 
- 푸터 이메일 변경
- 큐레이션 gradient 적용
- 
> 기록하며 개발하기!
- 
-

[FIX] 자잘한 수정사항 반영 완료

---

src/apis/filter/axios.ts
src/apis/instance.ts
src/apis/ranking/axios.ts

close #164
- 로그인 상태에 따라 axios인스턴스 선택을 위한 함수를 만들었습니다. 
```
export const getAxiosInstance = () => {
const isLoggedIn = !!localStorage.getItem('Authorization');
return isLoggedIn ? privateInstance : instance;
};
```
- 로컬 스토리지를 통해서 현재 로그인 상태 판단 하게 해두었습니다.
> 기록하며 개발하기!
- 
-

[FEAT] privateinstance, Instance 나눠서 분기처리 로직 구현

---

src/apis/templeImages/axios.ts
src/apis/templeImages/index.ts
src/apis/templeImages/type.ts
src/components/carousel/detailCarousel/DetailCarousel.tsx
src/components/carousel/detailCarousel/DetailImage.tsx
src/components/common/button/buttonBar/buttonBar.css.ts
src/components/common/pageName/pageName.css.ts
src/components/templeDetail/templeReview/TempleReview.tsx
src/components/userInfo/userInfo.tsx
src/hooks/useNavigateTo.tsx
src/pages/templeDetailPage/TempleDetailPage.tsx
src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
src/pages/templeDetailPage/templePhoto/TemplePhotoPage.tsx
src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts

close #145 
- 템플스테이 이미지 url get api 연결했습니다.
- params로 url의 템플스테이 id가져와 사용했습니다.
- total이 null일 경우 0으로 되도록 설정했습니다.
- 
> 기록하며 개발하기!
- 
-

[FEAT] 템플스테이 이미지 url api 연결

---

src/components/carousel/popularCarousel/PopularCarousel.tsx
src/components/carousel/popularCarousel/popularCarousel.css.ts
src/pages/homePage/HomePage.tsx

close #161 
- 캐러셀 인덱스 수정
- 
> 기록하며 개발하기!
- 자기 전에 푸시를 꼭 하자 
-

[FIX] 캐러셀 인덱스 수정

---

src/apis/wish/index.ts
src/components/carousel/popularCarousel/PopularCarousel.tsx
src/components/common/button/buttonBar/ButtonBar.tsx
src/components/common/button/flowerBtn/FlowerBtn.tsx
src/components/common/pageName/PageName.tsx
src/components/templeDetail/templeTopbar/TempleTopbar.tsx
src/pages/RedirectionPage/RedirectionPage.tsx
src/pages/searchResultPage/SearchResultPage.tsx
src/pages/templeDetailPage/TempleDetailPage.tsx
src/pages/wishList/WishListPage.tsx

close #169 
- 상세페이지에서 위시 추가, 삭제하는 부분을 연결했습니다.
- 
> 기록하며 개발하기!
- 
-

[FEAT] 위시 추가 삭제 연결

---

src/apis/instance.ts
src/apis/templeDetail/index.ts
src/components/card/templeStayCard/TempleStayCard.tsx
src/components/card/templeStayCard/searchCardList/SearchCardList.tsx
src/components/card/templeStayCard/wishCardList/WishCardList.tsx
src/pages/searchPage/SearchPage.tsx

- 검색 결과에서 템플스테이 상세페이지로 navigate 추가
- 검색 결과에서 템플스테이 상세페이지로 navigate 추가
- 템플스테이 상세 정보 불러오는 api 쿼리 키 수정
> 기록하며 개발하기!
- 
-

[FEAT] 검색 결과에서 템플스테이 상세페이지로 navigate 추가

---

src/components/card/templeStayCard/infoSection.css.ts
src/components/search/recentBtn/RecentBtnBox.tsx
src/pages/homePage/homePage.css.ts

- 커밋 메세지 보세용 
- 
> 기록하며 개발하기!
- 
-

[FIX] 이것저것 

---

src/components/card/lookCard/LookCard.tsx
src/components/detailTitle/DetailTitle.tsx
src/components/detailTitle/detailTitle.css.ts
src/components/search/recentBtn/RecentBtnBox.tsx
src/constants/curationInfo.ts
src/hooks/useFilter.ts

- 
- 커밋 메시지 확인 바람 ^^ ,,
> 기록하며 개발하기!
- 
-

[FIX] 이것저것 2탄

---

src/components/common/pageName/PageName.tsx
src/pages/homePage/HomePage.tsx
src/pages/homePage/homePage.css.ts
src/pages/loginPage/LoginPage.tsx
src/pages/searchResultPage/SearchResultPage.tsx
src/pages/templeDetailPage/TempleDetailPage.tsx
src/router/PrivateRoute.tsx

close #192
- 홈화면에서 터치가 안되는 문제를 해결하였습니다.
- 이전으로 이동하는 로직을 수정하였습니다. 
- 
> 기록하며 개발하기!
- 
-

[FIX] QA 대응 

---

src/components/common/modal/Modal.tsx
src/components/userInfo/userInfo.tsx
src/pages/homePage/HomePage.tsx
src/pages/loginPage/ModalLoginPage.tsx
src/pages/loginPage/modalLoginPage.css.ts
src/pages/myPage/MyPage.tsx
src/pages/myPage/myPage.css.ts
src/pages/searchResultPage/SearchResultPage.tsx
src/pages/templeDetailPage/TempleDetailPage.tsx
src/router/Router.tsx

close #200 
- 모달 후 연결되는 로그인페이지 생성
- 로그인 안내 모달에서 버튼 색이 반대로 보이는 문제 수정
- 200이슈는 나다.
> 기록하며 개발하기!
- 
-

[FEAT] 모달 후 연결되는 로그인페이지 생성

---

src/components/search/recentBtn/RecentBtnBox.tsx
src/components/search/searchBar/searchBar.css.ts
src/hooks/useFilter.ts

close #201 
검색 QA 반영했습니다
- 최근 검색어 클릭 시 다시 검색되게 수정
- 비로그인 검색어 로컬스토리지 저장 로직 수정 (중복 저장 x, 순서 보장)
- 검색 아이콘 중앙정렬 수정 
- 
> 기록하며 개발하기!
- 
-

[FIX] 검색 QA 반영

---

src/apis/instance.ts
src/apis/user/axios.ts
src/components/filter/filterTypeBox/FilterTypeBox.tsx
src/hooks/useFilter.ts
src/pages/welcomePage/WelcomePage.tsx

close #206 
- privateInstance의 interceptor에서 리프레시 토큰 요청 관련해서 제대로 엑세스토큰을 받아오지 못하고 있었어서 해당 문제를 해결했습니다.
- 검색어 공백을 지우고 검색하는 로직 추가
- 
> 기록하며 개발하기!
- 
-

[FIX] 엑세스 토큰 재요청 로직 수정

---

src/apis/search/index.ts
src/components/search/recentBtn/RecentBtnBox.tsx

- 새로고침 해야 최근 검색어 데이터 갱신되는 문제 해결 및 로딩, 에러화면 추가
- 쿼리 키 무효화로 해결하고 싶었는데 못 함 ,, 우선 refetch 하는 걸로 했습니다 
> 기록하며 개발하기!
- 
-

[FIX] 새로고침 해야 데이터 갱신되는 문제 해결 및 로딩, 에러화면 추가

---

src/styles/global.css.ts

[DEPLOY] dev to main

---

src/components/common/modal/modal.css.ts
src/pages/searchResultPage/SearchResultPage.tsx
src/pages/searchResultPage/searchResultPage.css.ts

close #222 
- 로띠 패딩 추가했습니다
- 
> 기록하며 개발하기!
- 
-

[FIX] QA 3차 대응

---

README.md

close #211  
- 리드미 최신화
- 제가 빠트린 본인 파트 내용있으면 넣어주세요
> 기록하며 개발하기!
- 
-

[DOCS] readme 서비스 기능 추가 및 최신화

---

index.html

close #175 
- ga 코드를 html에 추가해두었습니다.
- Google Tag Manager 측정이 가능하도록 하였습니다.
- 
> 기록하며 개발하기!
- 
-

[FEAT] ga 붙이기

---

src/pages/onboardingPage/OnboardingPage.tsx
src/pages/onboardingPage/onboardingPage.css.ts

close #227 
- 모바일 브라우저 100vh 오류 수정을 적용해 보았습니다.
- 
> 기록하며 개발하기!
- 
-

[FIX] 온보딩 하단 버튼 위치 조정

---

src/pages/templeDetailPage/blogReview/BlogReviewPage.tsx
src/pages/templeDetailPage/templePhoto/templePhotoPage.css.ts
src/pages/wishList/WishListPage.tsx
src/pages/wishList/wishListPage.css.ts

close #226
- 블로그 전체 보기 했을 때 위로 안넘어감
- 사진 페이지 상단 패딩 줘야함
- 위시리스트 상단 고정
- 
> 기록하며 개발하기!
- 
-

[FIX] QA 4차 반영

---

src/components/filter/priceSlider/PriceSlider.tsx
src/hooks/debounce.ts
src/hooks/useFilter.ts

close #214
- 가격 상태를 쿼리키로 등록해놔서 가격 상태가 변경될때마다 api호출이 발생하여 가격 로컬상태와 전역상태 구분하여 전역상태 설정은 디바운스 적용하였습니다.
- 데이터를 로드하는 동안 카운트에 0이 떠서 로드하는 동안은 이전 데이터를 유지하도록 하였습니다.
- 
> 기록하며 개발하기!
- 
-

[FIX] 가격 슬라이드 로직 수정

---

vercel.json

close #281
- 기존에 정적 페이지 방식으로 vercel.json이 설정되어 있어서 해당 부분을 next.js에 대한 설정으로 수정했어요
- 
> 기록하며 개발하기!
- 
-

[FIX] versel.json 수정

---

public/assets/svgs/icn_arrow_small_gray_down.svg
public/assets/svgs/icn_check_black.svg
public/assets/svgs/index.ts
src/app/searchResult/page.tsx
src/app/searchResult/searchResultPage.css.ts
src/components/common/button/sortBtn/SortBtn.tsx
src/components/common/button/sortBtn/sortBtn.css.ts
src/constants/sort.ts

close #283 
- `BottomSheet` 컴포넌트를 사용하여 정렬 기능 UI 구현하였습니다.
- 관련 API가 어떻게 수정될지는 아직 정해지지 않았지만, `sort=recommend`처럼 문자열 값을 전달하는 방식일 것으로 가정하고 정렬 관련 상수를 sort.ts로 분리하였습니다.
- 정렬 옵션을 사용할 때 별도의 매핑 함수 없이 value → label을 바로 참조할 수 있도록 SORT_OPTIONS와 SORT_LABELS를 분리하였고, 타입 안정성을 위하여 Record type을 사용하였습니다
> 기록하며 개발하기!
- 
-  [[TS] Enum VS. As Const](https://velog.io/@hamjw0122/TS-Enum-VS.-As-Const)

[FEAT] 정렬 기능 UI 구현

---

src/middleware.ts

- NODE_ENV 기준으로 쿠키 분기처리 -> 테스트 해보고 안되면 다시 롤백하겠음
- 
> 기록하며 개발하기!
- 
-

[FIX] middleware에서 쿠키가 undefined로 읽히는 이슈 대응

---

src/components/card/reviewCard/reviewCard/ReviewCard.tsx

close #319
- 
- 
> 기록하며 개발하기!
- 
-

[FIX] 블로그 리뷰 API 연동 오류 

---

next.config.ts
src/apis/templeInfo/prefetch.ts

close #323 
- import 순서로 인한 Build에러로 배포가 실패하고 있었습니다
- eslint때문에 배포가 안된는 상황 방지를 위해서(build 에러가 아닌 lint에러니깐,,) eslint 체크는 꺼두겟슴다!
- 
> 기록하며 개발하기!
- 
-

fix: build에러 수정
